# Pàgina principal
esdib_inventari_main:
    path:     /
    defaults: { _controller: ESDIBInventariBundle:Main:index }

# Mostra tots els Items de la taula 'Items'
listitems:
    path:     /items/
    defaults: { _controller: ESDIBInventariBundle:ListItems:show }

# Selecciona un Item
item:
    path: /item/{id}
    defaults: { _controller: ESDIBInventariBundle:Item:show }