# Pàgina principal
esdib_inventari_main:
    path:     /
    defaults: { _controller: ESDIBInventariBundle:Main:index }

# Llista els items de l'Inventari
inventari_llista_items:
    path: /items
    defaults: { _controller: ESDIBInventariBundle:Items:index }

# Selecciona un Item
item:
    path: /item/{id}
    defaults: { _controller: ESDIBInventariBundle:Item:show }