security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    toni:  { password: toni, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            #pattern:    ^/demo/secured/
            pattern:    ^/
            # anonymous: ~  xtoni No volem usuaris anònims en general
            anonymous: ~
            form_login:
#                check_path: _security_check
#                login_path: _demo_login
                login_path: login
                check_path: login_check
            logout:
                path:   /logout
                target: /
        # Redirigir cap a login quan usuari entra a pàgina sense acccés:
        # http://stackoverflow.com/questions/13577297/force-user-login-in-symfony-2
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    # Autorització a carpetes reservades a un determinat role, ex_ ROLE_ADMIN
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: {ROLE_ADMIN, ROLE_USER} }
        # He de poder fer LOGIN a pesar de no estar Autenticat
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }        