parameters:
    esdib.controller.listitems.class: ESDIB\InventariBundle\Controller\ListItemsController

services:
    esdib.main_items_controller:
        class:  "%esdib.controller.listitems.class%"

